### ISSUE TITLE
Deleting a subscriptions can't find the Sale object

### ISSUE THREAD

**Issue by maxgronlund** [payolapayments/payola#117]
payola.subscribe 'customer.subscription.deleted' do |event|
    sale = Sale.find_by(stripe_id: event.data.object.id)

NameError - uninitialized constant Sale

**Comment by maxgronlund** [comment]
If I look in the db from the console:

ap Payola::Sale.last
  Payola::Sale Load (0.2ms)  SELECT  "payola_sales".* FROM "payola_sales"  ORDER BY "payola_sales"."id" DESC LIMIT 1
#<Payola::Sale:0x007f9ec9966f08> {
                      :id => 2,
                   :email => "test02@pixelsonrails.com",
                    :guid => "9ihb2",
              :product_id => 3,
            :product_type => "Plan",
              :created_at => Mon, 20 Apr 2015 07:55:54 UTC +00:00,
              :updated_at => Mon, 20 Apr 2015 07:55:54 UTC +00:00,
                   :state => "finished",
               :stripe_id => "ch_15tZkoDCWuUtTcRT9RMDRPGq",
            :stripe_token => "invoice",
              :card_last4 => "4242",
         :card_expiration => nil,
               :card_type => "Visa",
                   :error => nil,
                  :amount => 999,
              :fee_amount => 421,
               :coupon_id => nil,
                  :opt_in => nil,
          :download_count => nil,
            :affiliate_id => nil,
        :customer_address => nil,
        :business_address => nil,
      :stripe_customer_id => nil,
                :currency => "usd",
    :signed_custom_fields => nil,
                :owner_id => 2,
              :owner_type => "Payola::Subscription"
}

i can see the 
:stripe_id => "ch_15tZkoDCWuUtTcRT9RMDRPGq",

On the stripe dashboard i can see https://dashboard.stripe.com/test/events 
the cancel subscription

when I open it
https://dashboard.stripe.com/test/subscriptions/sub_SAME_AS_ABOVE

i can see
{
object:
id: sub_65lbQPxaW3vqJy

**Comment by peterkeen** [comment]
I'm not sure what to say about the second part of this, but the first part is because `event.data.object` for a `customer.subscription.deleted` is a `Stripe::Subscription` (associated with `Payola::Subscription`), not a `Stripe::Charge` (associated with `Payola::Sale`).

**Comment by enderwiggens** [comment]
I am having the same issue.  Getting "NameError - uninitialized constant Sale" with a webhook.  Any update on this?
