### ISSUE TITLE
Question: Does Payola support two-step payments?

### ISSUE THREAD

**Issue by jordigg** [payolapayments/payola#124]
Is it possible with this gem to authorize a payment and charge it later?
https://stripe.com/blog/auth-capture

Thanks!

**Comment by peterkeen** [comment]
It would take some work but it's possible. We'd have to add a few things:

* some way to indicate that this charge shouldn't be captured immediately (maybe on the product class? or pass through the view like you had in #126)
* pass that to the `capture` param when creating the `Stripe::Charge`
* another state for `Payola::Sale` between `processing` and `finished` maybe called `authorized`
* a new service that calls `capture` on the `Stripe::Charge` for an authorized `Payola::Sale`
* tests for all of the above

**Comment by jordigg** [comment]
That's great! I'm new to rails so I'm learning by doing. I'll put some thought on that and try to make it work :+1: 

Thanks!

**Comment by jordigg** [comment]
I'm already working on it. Is there any easy way to disable the background jobs to be able to test and rise errors?

Thanks and sorry for my noob questions :smile:

**Comment by jordigg** [comment]
Created a new service and partial to show a button to capture the authorized payment. Still finishing and adding more things. I have it here: https://github.com/jordigg/payola/tree/two-step-payments

I have changed some more code on the charge_card service to avoid creating duplicating customers on the sales method. I think it was only working fine with subscriptions.

I may need some help with the tests :smile: any help will be much appreciated.

**Comment by gsdean** [comment]
what's the latest on this? Were you able to implement the tests?
