### ISSUE TITLE
What is the best way to handle subscription cancellation after non payment?

### ISSUE THREAD

**Issue by bcasci** [payolapayments/payola#133]
Great work on the gem! Question. Stripe will cancel a subscription after enough payment failures. What's the best way to let your app know about event? Configure a listener for 'customer.subscription.deleted' and have the listener call `Payola::CancelSubscription`, `Payola::SyncSubscription` or something else?

**Comment by peterkeen** [comment]
It's flexible within Stripe so Payola doesn't hold an opinion, but adding a
`customer.subscription.deleted` listener that calls
`Payola::SyncSubscription` is definitely the thing to do with the default
settings.

**Comment by bcasci** [comment]
Thanks man! That's what I figured.
