### ISSUE TITLE
rake db:migrate fails in a multi tenant environment

### ISSUE THREAD

**Issue by ashwinputhige** [payolapayments/payola#142]
I am using Apartment gem for creating a multi tenant environment.
A tenant is created using :
`Apartment::Tenant.create('new_tenant')`

This command creates al the tables(I believe it creates them from schema.rb) and hence creates all the tables including Payola tables.

Now, if I create a new table : `rails g model anything:string` and then `run rake db:migrate`,  Payola tries to run its migrations which will fail because the Payola tables already exist.

The error is : 

```
Migrating new_tenant tenant

== 20141001170138 CreatePayolaSales: migrating ================================

-- create_table(:payola_sales)

rake aborted!

StandardError: An error has occurred, this and all later migrations canceled:



PG::DuplicateTable: ERROR:  relation "payola_sales" already exists

: CREATE TABLE "payola_sales" ("id" serial primary key, "email" character varying(191), "guid" character varying(191), "product_id" integer, "product_type" character varying(100), "created_at" timestamp, "updated_at" timestamp, "state" character varying, "stripe_id" character varying, "stripe_token" character varying, "card_last4" character varying, "card_expiration" date, "card_type" character varying, "error" text, "amount" integer, "fee_amount" integer, "coupon_id" integer, "opt_in" boolean, "download_count" integer, "affiliate_id" integer, "customer_address" text, "business_address" text)

```

So,
- Is there a way to tell Payola to not run its migrations as all tables have been created already?
- Can I set a flag to indicate Payola migrations ran successfully?
- Any other way to fix this?

Peter's reply
Payola migrations are added via an initializer: 

https://github.com/peterkeen/payola/blob/master/lib/payola/engine.rb#L13-L19

There's currently no flag for that, but I think we could add one that checks some setting on the `Payola` object. Could you create a GitHub issue to track, please?

--Pete

**Comment by ashwinputhige** [comment]
Here's a [workaround](https://github.com/influitive/apartment/issues/243#issuecomment-119436735). Copy migrations from schema_migrations in  "public" tenant to "yourtenant". Hoping this info can help you fix this.

**Comment by joekr** [comment]
I'm seeing this issue as well. Adding a new migration, then running ```rake db:migrate``` raises the same error.

**Rails** 4.2
**Payola** 1.3.2
