### ISSUE TITLE
AASM::InvalidTransition in SubscriptionsController#create Event 'fail' cannot transition from 'active'

### ISSUE THREAD

**Issue by mits87** [payolapayments/payola#154]
Hello, 

I was installed payola gem and installed.
All it's fine but when I create new subscribtion I have got error:

> AASM::InvalidTransition in SubscriptionsController#create Event 'fail' cannot transition from 'active'
> Extracted source (around line #138):
> 
> ```
> if AASM::StateMachine[self.class].config.whiny_transitions
>   raise AASM::InvalidTransition.new(self, event_name) 
> else
>   false
> end
> ```
> 
> Extracted source (around line #83):
> 
> ```
>     end
>   else
>     aasm_failed(event_name, old_state)
>   end
> rescue StandardError => e
>   event.fire_callbacks(:error, self, e, *process_args(event, aasm.current_state, *args)) || raise(e)
> ```
> 
> Extracted source (around line #175):
> 
> ```
>     def aasm_fire_event(name, options, *args, &block)
>       success = options[:persist] ? self.class.transaction(:requires_new => requires_new?) { super } : super
> 
>       if success && options[:persist]
>         event = self.class.aasm.state_machine.events[name]
> ```
> 
> Extracted source (around line #213):
> 
> ```
>       yield
>     else
>       transaction_manager.within_new_transaction(options) { yield }
>     end
>   rescue ActiveRecord::Rollback
>     # rollbacks are silently swallowed
> ```
> 
>  ....

My version of: 
ruby '2.2.2'
gem 'rails', '4.2.3'

**Comment by rikkipitt** [comment]
@mits87, I encountered this today when testing with Stripe's test failure card number: 4000 0000 0000 0341

https://support.stripe.com/questions/test-failed-invoice-payment

Did you get anywhere in figuring this out? I'm using Payola @c6ad165

**Comment by rikkipitt** [comment]
Mentioned here: #136 

I'll try 1.4.0!
