### ISSUE TITLE
NameError (uninitialized constant Sale)

### ISSUE THREAD

**Issue by enderwiggens** [payolapayments/payola#155]
Hello 

I am using the following code for stripe webhooks in Payola.rb as provided in the configuration documentation:

Payola.configure do |payola|
  payola.subscribe 'customer.subscription.created' do |event|
    sale = Sale.find_by(stripe_id: event.data.object.id)
    SaleMailer.admin_receipt(sale.guid)
  end
end

However, I get this error:

NameError (uninitialized constant Sale):
  config/initializers/payola.rb:8:in `block (2 levels) in <top (required)>'

**Comment by enderwiggens** [comment]
Also - it looks like this issue has been cropping up in quite a few different places.  In my case I am using the subscription but have tried changing Sale to Subscription with no luck.

**Comment by nfm** [comment]
@enderwiggens the documentation should have read:

```ruby
sale = Payola::Sale.find_by(stripe_id: event.data.object.id)
```

I've just updated this now :)

**Comment by enderwiggens** [comment]
This worked - thanks!

On Wed, Sep 2, 2015 at 9:58 PM, Nicholas Firth-McCoy <
notifications@github.com> wrote:

> @enderwiggens <https://github.com/enderwiggens> the documentation should
> have read:
>
> sale = Payola::Sale.find_by(stripe_id: event.data.object.id)
>
> I've just updated this now :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peterkeen/payola/issues/155#issuecomment-137300606>.
>



-- 

Kevin Fleming

Founder
Contena.co
