### ISSUE TITLE
Support for selling multiple products all at once

### ISSUE THREAD

**Issue by oboxodo** [payolapayments/payola#162]
What if I want to let the user choose from a set of products and buy them all at once? Any plans to support that? This is currently a major impediment for me to use Payola. Any workaround you can think of?

If you/we were to try updating Payola to support this, I imagine changing `Sale`'s `belongs_to :product` to some `has_and_belongs_to_many` or `has_many :products, through: :sale_lines` or something like that.

**Comment by peterkeen** [comment]
Make your "product" be a shopping cart, then have that implement the
interface that Sellable needs and does the has many through to the real
products.

**Comment by oboxodo** [comment]
Gotcha.

On Thu, Sep 24, 2015 at 7:11 PM, Pete Keen <notifications@github.com> wrote:

> Make your "product" be a shopping cart, then have that implement the
> interface that Sellable needs and does the has many through to the real
> products.
>
> On Thursday, September 24, 2015, Diego Algorta <notifications@github.com>
> wrote:
>
> > What if I want to let the user choose from a set of products and buy them
> > all at once? Any plans to support that? This is currently a major
> > impediment for me to use Payola. Any workaround you can think of?
> >
> > If you/we were to try updating Payola to support this, I imagine changing
> > Sale's belongs_to :product to some has_and_belongs_to_many or has_many
> > :products, through: :sale_lines or something like that.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/peterkeen/payola/issues/162>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peterkeen/payola/issues/162#issuecomment-143063638>.
>



-- 
Diego Algorta : ob.oxo.do
