### ISSUE TITLE
Create Card Service

### ISSUE THREAD

**Issue by MarkMurphy** [payolapayments/payola#175]
In your create card service, I'm curious if you're only checking fingerprints to prevent trying to use the same token twice?

If that were the case, why not do this instead:

``` ruby
customer.sources.create({source: token}, {
  idempotency_key: Digest::SHA1.hexdigest("sources.create:#{token}")
}) 
```

**Comment by jharbert** [comment]
@MarkMurphy - I wasn't aware of this header.  You solution should be fine granted that the token stays the same with the same card credentials. :+1:

**Comment by MarkMurphy** [comment]
I suppose one potential drawback depending on what the developer prefers... is if the user adds the same card using another token. This would give them a duplicate card in Stripe. 

Maybe a combination of the two then:

```ruby
fingerprint = Stripe::Token.retrieve(token).try(:card).try(:fingerprint)
customer = Stripe::Customer.retrieve(stripe_customer_id)

sources = Array(customer.sources.select{|source| source.fingerprint == fingerprint})

if sources.any?
  sources.first
else
  customer.sources.create({source: token}, idempotency_key: Digest::SHA1.hexdigest("sources.create:#{token}"))
end
```

Note though that if the customer has more cards than are returned in the first retrieval, this code would still potentially add a duplicate card.
