### ISSUE TITLE
How to force user to have no more than one subscription?

### ISSUE THREAD

**Issue by camilleroux** [payolapayments/payola#193]
Hi,

Currently, a user can have multiple subscriptions. 
I'm using the Checkout button. Is it possible to validate it to have no more than one subscription per user?

**Comment by joshmn** [comment]
slap this baby in an initializer to patch 
```
module Payola
  class Subscription < ActiveRecord::Base
  
    validates :owner, with: :ensure_one_subscription, :on => :create 

    def ensure_one_subscription
      self.errors.add(:base, "Sorry, can't have multiple of these babies.") unless self.owner.subscriptions <= 1
    end
  end
end
```

untested (and I don't use payola), but I think you get the idea.

**Comment by nfm** [comment]
@camilleroux I did something like this:

```ruby
  config.charge_verifier = lambda do |sale, custom_fields|
    account = Account.find(custom_fields[:account_id])

    # Prevent more than one active subscription for a given account
    if sale.is_a?(Payola::Subscription) && account.payola_subscriptions.active.any?
      raise "This account already has an active subscription"
    end

    # Associate the sale with the account
    sale.owner = account
    sale.save!
  end
```

We look up the account associated with the sale using the `custom_fields` to pass in an `account_id`.
Then if the sale is for a subscription and the account already has an active subscription, raise an exception.

In the front-end, we use similar logic (i.e. `account.payola_subscriptions.active.any?`) to determine whether to show 'Sign up' buttons or not.
