### ISSUE TITLE
Timestamps need to specify an option for `null` in rails 4.2.5.1

### ISSUE THREAD

**Issue by Showtimes** [payolapayments/payola#203]
When running a new migration on rails `4.2.5.1` the following error appears:

```
#timestamps` was called without specifying an option for `null`. In Rails 5, this behavior will change to `null: false`. You should manually specify `null: true` to prevent the behavior of your existing migrations from changing.
```

Following this PR: https://github.com/rails/rails/pull/16481 null:true should be manually entered.

**Comment by peterkeen** [comment]
@Showtimes Would you be willing to send a PR in for this?
