### ISSUE TITLE
Stripe keys not found with Figaro

### ISSUE THREAD

**Issue by gilomen2** [payolapayments/payola#205]
I ran into an issue using [Figaro](https://github.com/laserlemon/figaro) for environment variables. Per the [Configuration Options](https://github.com/peterkeen/payola/wiki/Configuration-options) documentation, you should be able to set the STRIPE_SECRET_KEY and STRIPE_PUBLISHABLE_KEY in environment variables and they will be detected and used, but they were not being found. This was resulting in 500s when receiving Stripe webhooks, with the error "TypeError: normalize opts expects a string or a hash."

I don't see anywhere in the documentation that Figaro is explicitly supported, but I wanted to put this out there in case anyone else runs into this issue as the error text is not super helpful in debugging.

Rails 4.2.3
Ruby 2.2.3
Figaro 
payola-payments 1.3.0
figaro 1.1.1 
stripe 1.35.0
stripe_event 1.5.0
### Configuration needed to resolve:

```
#config/initializers/payola.rb
Payola.configure do |config|
  config.secret_key = ENV['STRIPE_SECRET_KEY']
  config.publishable_key = ENV['STRIPE_PUBLISHABLE_KEY']
end
```

```
#config/initializers/stripe.rb
Rails.configuration.stripe = {
    :publishable_key => ENV['STRIPE_PUBLISHABLE_KEY']
    :secret_key      => ENV['STRIPE_SECRET_KEY']
}

Stripe.api_key = ENV['STRIPE_SECRET_KEY']
```

**Comment by peterkeen** [comment]
Thanks @gilomen2. Could you post your `Gemfile`? I think this may be an issue where Figaro is getting loaded after Payola so the env vars aren't getting set before Payola loads.

**Comment by gilomen2** [comment]
@peterkeen here's my `Gemfile`. Let me know if I can provide any other info.

```
source 'https://rubygems.org'

gem 'rails', '4.2.3'

group :production do
  gem 'pg'
  gem 'rails_12factor'
end

group :development do
  gem 'sqlite3'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'railroady'
end

gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass'
gem 'font-awesome-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'figaro'
gem 'devise'
gem 'pundit'
gem 'carrierwave'
gem 'mini_magick'
gem 'fog'
gem 'faker'
gem 'stripe'
gem 'redcarpet'
gem 'will_paginate-bootstrap'
gem 'formvalidation-rails'
gem 'data-confirm-modal', github: 'ifad/data-confirm-modal'
gem 'phonelib'
gem 'time_splitter'
gem 'timeliness'
gem 'validates_timeliness'
gem 'payola-payments'
gem 'stripe-rails'
gem 'money'
gem 'time_difference'

gem 'web-console', group: :development

group :development, :test do
  gem 'byebug'
  gem 'pry-rails'
  gem 'rubocop', require: false
  gem 'rspec-rails', '~> 3.0'
  gem 'spring'
end
```

**Comment by peterkeen** [comment]
Try putting Figaro at the very top after the source line and removing the
patches you added to the config.

**Comment by eliotsykes** [comment]
Closing for now - please reopen if you discover anything to add.
