### ISSUE TITLE
No support for payments without CC information

### ISSUE THREAD

**Issue by frozeek** [payolapayments/payola#224]
Hi. I'm trying to implement the purchase of a second subscription for an already existing customer using Payola.

Implementing the first purchase is easy using the "payola-onestep-subscription-form" and asking the customer for his/her credit card information. That will send that info to Stripe, get the token and post it to our servers along with the other form data.

But what if the first subscription is cancelled and the user wants to reactivate it by purchasing a new subscription? Do we need to ask the user for his/her credit card information all over again?

Is there a way of using just the stripe_customer_id for this? I tried to use the same Payola form to leverage the background subscription processing but I couldn't figure out how.

What would you recommend for this particular use case?

Thanks!

**Comment by Alagaesia93** [comment]
+1

**Comment by eliotsykes** [comment]
Hi @frozeek - please share any details of what you found out to avoid asking for credit card details multiple times, many thanks.

**Comment by peterkeen** [comment]
If you create a `Payola::Subscription` record with a `stripe_customer_id` that already exists (i.e. you copy it from another record) and pass it to `Payola::StartSubscription` it will do the right thing and re-use the customer.

**Comment by peterkeen** [comment]
Also, if you set the `owner` attribute to a something that already has an attached `Payola::Subscription` it will do the right thing, look up the owner's subscription and re-use that `stripe_customer_id`.
