### ISSUE TITLE
Best way to seed test data

### ISSUE THREAD

**Issue by benphelps** [payolapayments/payola#226]
I need to seed a year's worth of test data and there isn't a clear way to seed the Payola data.  Does anyone have experience with this or know of a clean way to do it?

**Comment by eliotsykes** [comment]
An option that might work for your situation only if you've got an existing database with data for the Payola tables. 

1. Import a copy of the db into your local environment
2. Use the seed_dump gem to dump the data to a ruby file
3. Edit the seed file created in step 2 to anonymize the data and remove any sensitive values (e.g. Stripe customer ids)
4. Use this seed file to populate test/dev db (possibly with the seed-fu gem)

**Comment by eliotsykes** [comment]
Closing for now - please reopen if you discover anything to add.
