### ISSUE TITLE
Undefined method 'tax_percent='

### ISSUE THREAD

**Issue by morgler** [payolapayments/payola#227]
I added payola (1.4) to my rails app. I also added a subscription controller and form as described in https://github.com/peterkeen/payola/wiki/Subscriptions. When I submit this form, I see that it goes through to stripe.com and then the SubscriptionsController's create method is called. This then throws the following error:

```
NoMethodError - undefined method `tax_percent=' for #<Payola::Subscription:0x007fa56db0d168>:
  activemodel (4.2.3) lib/active_model/attribute_methods.rb:433:in `method_missing'
  payola-payments (1.4.0) app/services/payola/create_subscription.rb:25:in `block in call'
```

It seems that Payola::Subscription has no tax_percent attribute, but the Payola::CreateSubscription service seems to assume it should have that attribute.

Is this a bug or am I missing something?

**Comment by JamesDullaghan** [comment]
Running into the same issue. It seems the last two migrations aren't included when the migrations are appended but have not found a culprit or a fix. https://github.com/peterkeen/payola/blob/master/lib/payola/engine.rb#L15

Pointing the gem to the github repo **sometimes** resolves the issue.

**Comment by eliotsykes** [comment]
I've also encountered the Payola migrations only running some of the time. Like @JamesDullaghan, I've not yet found the culprit.

Alternative workarounds you might want to try:
- Always run `bin/rake db:migrate` a 2nd time. I think I've seen it where the Payola migrations are picked up on the 2nd run of the task.
- Rebuild the db from scratch with one of:
  - `bin/rake db:drop db:create; bin/rake db:migrate;` (may need a 2nd db:migrate) OR
  - `bin/rake db:drop db:create db:schema:load db:migrate`

**Comment by abrambailey** [comment]
@peterkeen Do you know what the issue is here?

**Comment by abrambailey** [comment]
Nevermind, I was just upgrading the gem and needed to re-run the migrations
