### ISSUE TITLE
undefined method `subscriptions' for #<Stripe::Customer:0x007fd95d6a4530>

### ISSUE THREAD

**Issue by webmaster219** [payolapayments/payola#233]
subscription = Payola::CreateSubscription.call(params, place)
...
gem 'stripe-ruby-mock'
gem 'payola-payments'
gem 'sucker_punch'
...

form_for(@place, :url => place_set_plane_path, :html => { :role => 'form', |
    :class => 'payola-onestep-subscription-form',                                                                  |
    'data-payola-base-path' => payola_path,                                                                        |
    'data-payola-plan-type' => @place.subscription_plan.plan_class,                                                           |
    'data-payola-plan-id' => @place.subscription_plan.id}) 

How can I solve this issue?

**Comment by eliotsykes** [comment]
Hi @webmaster219,

Please review the Subscriptions wiki page in case there is a solution there: https://github.com/peterkeen/payola/wiki/Subscriptions

If the error continues to happen, please reply with the following details:
- full stack trace
- Gemfile
- Versions of any payola, stripe-related gems as specified in Gemfile.lock
- Any other code you think is relevant to the issue

Thanks, E.

**Comment by naterexw** [comment]
Check your User model associations:

if you have
```has_many :subscriptions...``` => ```user.subscriptions.active.any?``` (plural 'subscriptions' method will work)

else if you have
```has_one :subscription...``` => ```user.subscription.state == "active"``` (only singular 'subscription' method will work).  

You cannot use plural 'subscriptions' method on a singular association, you will get ```undefined method `subscriptions' for #<Stripe::Customer:0x007fd95d6a4530>``` error
