### ISSUE TITLE
Multiple subscriptions per customer

### ISSUE THREAD

**Issue by callmeahab** [payolapayments/payola#240]
Hi,

I'd like to know wether multiple subscription types are supported in payola?
If they're not i'd like to fork the project and add support for them, but in that case could i get some info on how i'd go around to doing that?

Thanks for the great work.

**Comment by eliotsykes** [comment]
@callmeahab I've not tried it myself, however I *suspect* it'd be possible, as it looks like Payola supports:
- multiple models that `include Payola::Plan`
- one subscription associates a plan with an owner (see associations defined here: https://github.com/peterkeen/payola/blob/2e787caf1dde0657f9fa657360bd9fe8f4faed2c/app/models/payola/subscription.rb#L16-L17)

**Comment by callmeahab** [comment]
Ok, will take a look at it. Thanks.

**Comment by charlesemarsh** [comment]
I'm also trying to achieve this, like you said, looks to be ok... would be good to have some docs for it

**Comment by callmeahab** [comment]
I've been busy these days, but i resolved this pretty easily. What i needed is not to connect multiple subscription types to a particular customer, just to a user.

And I achieved that by making two different models that inherit from `Payola::Plan`, and just let payola handle the subscriptions from there. Only other thing i changed was create a `Subscription` model that inherits from `Payola::Subscription`, to make it easier to make helper methods and scope for user, for easier querying.

**Comment by alexung** [comment]
Thanks for the solution above, but doesn't payola support multiple subscriptions per user already? https://github.com/payolapayments/payola/wiki/Subscriptions#subscription-quantity

**Comment by eliotsykes** [comment]
@alexung Correct, good find. Closing this issue as it seems to be resolved.
