### ISSUE TITLE
Explore removing status column on subscriptions table

### ISSUE THREAD

**Issue by eliotsykes** [payolapayments/payola#257]
Wondering if the `status` column on the `payola_subscriptions` table can be removed. There are 3 columns with state-related names:
1. `state` - used by aasm state machine
2. `stripe_status` - this represents the current status held by Stripe (possible values are trialing, active, past_due, canceled, unpaid)
3. `status` - research hasn't turned up its purpose yet

**Comment by Tongboy** [comment]
I just ran in to a related issue today. After addressing an account in a past due status within Stripe I was confirming the webhook worked correctly and updated the payola::subscription.

the `status` & `state` columns both indicate 'past_due' and the `stripe_status` column indicates the correct (after receiving the webhook) 'active' status.

I would have expected these columns to be somewhat in sync or their purposes clearly delineated. Which is the correct column to use? based on my findings I'd say the `stripe_status` column.

I'm happy to help update documentation to clarify the purpose of those columns or put together a pull request to remove one/some of them.
