### ISSUE TITLE
stripeToken required for new customer with paid subscription -- can't resolve

### ISSUE THREAD

**Issue by brycejohnston** [payolapayments/payola#270]
I have a Rails 5 app that will be used for subscriptions through payola/stripe. I followed the subscriptions guide, have payola 1.5.0 added and installed, setup payola initializer with secret_key and publishable_key, ran migrations, setup plans, etc and payola route is added to routes and payola is included in application.js. Payola header file is in the head of layout file and confirmed to be loading payola js and publishable_key:

<img width="988" alt="js" src="https://cloud.githubusercontent.com/assets/13186360/20312979/03b5ddf6-ab1b-11e6-9137-66d269194c1d.png">

Everytime I attempt to create a subscription, I get the stripeToken required for new customer with paid subscription error and its never even hitting Stripe API:

<img width="1050" alt="form_error" src="https://cloud.githubusercontent.com/assets/13186360/20312987/09c50b04-ab1b-11e6-8fb1-a13ced36fdac.png">

Any ideas what is happening or why it might not be getting the stripeToken? Thanks

**Comment by Tongboy** [comment]
strong params blocking the :stripeToken @ the controller?
