### ISSUE TITLE
NameError: uninitialized constant SaleMailer

### ISSUE THREAD

**Issue by k2xl** [payolapayments/payola#276]
SaleMailer - doesn't seem to exist?

**Comment by eliotsykes** [comment]
Hi @k2xl - thanks for reporting the issue. This looks like a problem with the [Configuration wiki page](https://github.com/payolapayments/payola/wiki/Configuration-options). 

`SaleMailer` was an example mailer that would be provided by the developers application. Payola doesn't have a `SaleMailer`. 

I've tried to fix the docs by replacing `SaleMailer` with `YourCustomMailer` so hopefully this will stop future developers hitting the same issue.
