### ISSUE TITLE
No such customer: a similar object exists in live mode, but a test mode key was used to make this request.

### ISSUE THREAD

**Issue by abrambailey** [payolapayments/payola#278]
I get the following error in development:
```
No such customer: cus_5tJLN1RqCwTM7R; a similar object exists in live mode, but a test mode key was used to make this request.
```
I'm really not sure what's causing this. It hasn't been an issue in the past, and my API keys are all set appropriately.

**Comment by eliotsykes** [comment]
Hi @abrambailey - if the error keeps appearing and in case you've not tried it yet, try the 3rd bullet point on the debugging page about stopping Spring and restarting the server: https://github.com/payolapayments/payola/wiki/Debugging

Closing for now.
