### ISSUE TITLE
Issue With Client Side Validation of CC when Upgrading to V1.5.0

### ISSUE THREAD

**Issue by NorCalDavid** [payolapayments/payola#279]
I am having difficulty upgrading Payola to V1.5.0 from V1.3.0 as it shows that the testing cards are invalid.  I had to create a custom subscription payment form for this App and I am wondering if you can provide me any details on what I would need to adjust to update my app to accommodate the Client Side Validation changes that were implemented in V1.5.0.  I am not sure what info/code you would need to help but if you let me know I can update this issue accordingly.

**Comment by eliotsykes** [comment]
Hi @NorCalDavid, a few things to consider trying - apologies if you've already tried them:

- Compare the app's form against whats on the Subscriptions wiki page in this section: https://github.com/payolapayments/payola/wiki/Subscriptions#forms
- Review the sample subscription form JS which has some client side validation in it https://github.com/payolapayments/payola/blob/48bad1ae7d39fb9eab5473d720987ea5891ac077/app/assets/javascripts/payola/subscription_form_onestep.js
- Look through server logs and output for any errors to debug
- Use the browser console to look for client-side errors to dbug

Please share how you get on here in the issue. If you've further questions please include as much detail including the errors and backtraces.

**Comment by eliotsykes** [comment]
Closing. Please reopen if there's further info to add.
