### ISSUE TITLE
Creating product on Stripe

### ISSUE THREAD

**Issue by Duleja** [payolapayments/payola#281]
When i create subscription with rails console, it gets created on the Stripe too.
But when i create product (also from the rails console), it is not created on the Stripe.
In test mode i can still buy that product.
Checkout button is working, charging is fine, web-hooks are all working, but i can't see product on the Stripe.
When creating product from the console i am inserting price, permalink, and name.
Any suggestions?

**Comment by eliotsykes** [comment]
@Duleja What's the code you're using for creating the product, and what's the code you're using for creating the subscription?

**Comment by Duleja** [comment]
Process is the same for both; from rails console:
Product.create(name: "product_name", price: product_price, permalink: "product_permalink")

for plan, just different fields:

Plan.create(amount: plan_amount, name: "plan_name", interval: "plan_interval", interval_count: plan_inteval_count, stripe_id: "plan_stripe_id")

in plan class i 
include Payola::Plan

and for product class
include Payola::Sellable

Sellable seems to not include creating product on the Stripe? If i am reading the ruby docs right...

**Comment by peterkeen** [comment]
`Payola::Sellable` doesn't create any objects within Stripe. What specific
Stripe object are you looking for it to create?

**Comment by Duleja** [comment]
Hello,
i would like to have product created on Stripe, the same way subscription is created when i create one in my database. Just so i can see that there is a product, looking from the Stripe dashboard, but maybe this is not necessary? Because like i said, checkout button for that product is working and payments are saved on Stripe at least in the test mod for i know for now :)

It was strange to see that on Stripe there is no products but people will be able to buy something i have in my database only? Please correct me if i am wrong

**Comment by peterkeen** [comment]
Payola's one-time payments support just makes Stripe::Charges as
appropriate. It doesn't have anything to do with Relay (Stripe's built-in
product/sku/order thing). We would gladly accept a GH issue to specifically
add Relay support :)
