### ISSUE TITLE
Zero Dollar Subscriptions

### ISSUE THREAD

**Issue by NorCalDavid** [payolapayments/payola#282]
Is it possible to process Zero Dollar Subscriptions without entering CC information on the payment page.  I am looking to implement complimentary subscriptions for certain users but it still requires them to enter a CC

**Comment by NorCalDavid** [comment]
I see this comment: https://github.com/payolapayments/payola/commit/0b0282fb256eba7247999fbf2b33f2ded567c311#comments.

Has this been implemented in Payola or would I need to try and implement this for my application to work?

**Comment by eliotsykes** [comment]
Hi @NorCalDavid - it looks like this is supported in Payola 1.4.0 or greater. What's the version of Payola you're using?

**Comment by eliotsykes** [comment]
Closing for now - please reopen if you discover anything to add.
