### ISSUE TITLE
Crashing with 'No route matches [GET] "/payola/events"'

### ISSUE THREAD

**Issue by stephenamsel** [payolapayments/payola#283]
I'm running Payola on Rails 5.0.1.
Immediately after calling the buy_path (transaction#create), it redirects to the Webhook controller, but using a GET instead of a POST, so there is no route. I had Payola working earlier on my system, before a bunch of updates, and I have no other gems with a Transactions Controller that might be interfering. Has anyone encountered this before or know what might cause this sort of error?

**Comment by stephenamsel** [comment]
Here is the full log-entry and stack-trace, with some parameters redacted:
Started POST "/payola/buy/confirmation/something-Feb-20-2017-Test_Organizer-46" for 127.0.0.1 at 2017-02-21 18:06:38 -0500
Processing by Payola::TransactionsController#create as */*
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"---REDACTED---", "stripeToken"=>"---REDACTED---", "stripeEmail"=>---REDACTED---", "product_class"=>"confirmation", "permalink"=>"---REDACTED---"}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."id" = $1 LIMIT $2  [["id", 82], ["LIMIT", 1]]
  CACHE (0.0ms)  SELECT  "users".* FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."id" = $1 LIMIT $2  [["id", 82], ["LIMIT", 1]]
Redirected to http://localhost:3000/payola/events?action=new&controller=users%2Fsessions
Completed 200 OK in 19ms (ActiveRecord: 0.5ms)


Started GET "/payola/events?action=new&controller=users%2Fsessions" for 127.0.0.1 at 2017-02-21 18:06:38 -0500
  
ActionController::RoutingError (No route matches [GET] "/payola/events"):
  
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
web-console (3.4.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.4.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `catch'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
puma (3.7.1) lib/puma/configuration.rb:232:in `call'
puma (3.7.1) lib/puma/server.rb:578:in `handle_request'
puma (3.7.1) lib/puma/server.rb:415:in `process_client'
puma (3.7.1) lib/puma/server.rb:275:in `block in run'
puma (3.7.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
Started GET "/payola/status/undefined" for 127.0.0.1 at 2017-02-21 18:06:38 -0500

Also, I just noticed that it looks like my guid is undefined. My sellable object is saved and contains a method:
def guid
  self.id
end

**Comment by eliotsykes** [comment]
Only a guess - are there any `redirect_path` methods on the models that could be returning the path `"/payola/events?action=new&controller=users%2Fsessions"`? If yes, try changing the method to return a different path.

**Comment by stephenamsel** [comment]
It was a good guess, but I just grepped for '/events?' in both my application and the gem, and didn't find anything. The other super-weird part is that I inserted a call to byebug and just a straight-up "deliberateerror" in Transactions#create, and neither activated. I'm going to look into why the guid is undefined. That looks like the first error and may have something to do with it.

I don't know if it makes a difference, but I am also using the Stripe API directly in my application to make delayed (automatic) charges, totally separately from the payments handled by Payola.

**Comment by eliotsykes** [comment]
Also try searching for `redirect_path` and see if you find any methods with that name. The code in that method may generate the `/payola/events?action=...` path programmatically rather than using a hardcoded `"/events?" string.

If you need further help, please include any relevant code in this issue.

**Comment by stephenamsel** [comment]
I found a relevant redirect_url, but it doesn't lead there. Here is the code in my sellable product (the class-name is "Confirmation") that relates to Payola:
```
belongs_to :event  
  has_paper_trail #https://github.com/airblade/paper_trail
  include Payola::Sellable  #https://github.com/peterkeen/payola/wiki/One-time-payments

  has_one :sale, class_name: Payola::Sale, as: :product
  
  def guid
    self.id
  end
  
  def redirect_url(sale)
    o = sale.product.event.organizer
    return organizer_path(o.id) #back to the Event Organizer dashboard
    #payment_path(id: sale.id)
  end
```
and here is the code in the initializer

```
Payola.configure do |config|
  config.secret_key = ENV['PAYOLA_SECRET_KEY'] #test secret key
  config.publishable_key = 'pk_test_weBdRhhjGzkV8ajmU39JMWZC'
  
  config.support_email = 'hr@estaffmatch.com'
  
  config.send_email_for :receipt, :admin_receipt, :refund, :admin_refund, :admin_failure
  
  Payola.configure do |payola|
    payola.charge_verifier = lambda do |sale, custom_data|      
      sale.product.update_attributes(paid: true, date: Date.today())      
    end
  end
  
  config.subscribe 'charge.refunded' do |event|
    sale = Payola::Sale.find_by(stripe_id: event.data.object.id)
    sale.refund! unless sale.refunded?
  end
end
```
There interface uses Payola's built-in checkout-modal with no custom fields.

**Comment by eliotsykes** [comment]
What's the output from `bin/rake routes`. (I'm wondering if there's some collision with Payola::Event and an `Event` model in the app).

**Comment by stephenamsel** [comment]
I thought about that too, but if it were a collision, it would have to be getting the path from one routes-entry and the method from another. Most of the routes have non-conflicting names because they are member-elements of another controller ("organizer"), but here are the ones that could start with "event" or "events" and could potentially conflict:

The standard paths from resources :events
payment GET  /event/:id/payment/:event_id(.:format) event#payment
create_workshift POST   /events/:event/workshift/create(.:format) work_shifts#create
update_workshift PUT    /events/:event/workshift/:id(.:format) work_shifts#update
destroy_workshift DELETE /events/:event/workshift/:id(.:format) work_shifts#destroy
rate_organizer PUT    /events/:event/workshift/:id/rate(.:format) work_shifts#rate_organizer

**Comment by eliotsykes** [comment]
This is a bit of a head scratcher. I'll leave the issue open for a few days, please report back anything you find to help anyone else that hits the same issue.

**Comment by eliotsykes** [comment]
Closing for now, please reopen and report back here if you discover anything further and good luck 👍

**Comment by stephenamsel** [comment]
I looked in my DB and found a record for a webhook that had no Stripe ID associated with it. No idea how it got there.

**Comment by stephenamsel** [comment]
I found that this bad route is not a new thing. My development.log shows many old "no route matches" errors, but these had not caused a crash, I guess because they were run asynchronously. Now I guess the non-existent route is being accessed in the request-cycle, so it is producing a crash-page.

**Comment by stephenamsel** [comment]
I loaded the page containing the "Pay Now" button with the current app, in which it doesn't work, and then checked out an old version that does. Proceeding from that point, the test-payment went through normally.

**Comment by stephenamsel** [comment]
Solved:
Cancan forbade customers from modifying Sale records so they were not saved and the tranaction was not enqueued. 
No Route Found seemed to come form
`head :not_found and return unless object`
in status_behavior.rb
