### ISSUE TITLE
Payola isn't initializing with new version of Turbolinks

### ISSUE THREAD

**Issue by dakotalightning** [payolapayments/payola#284]
$(document).on('page:change', PayolaCheckout.initialize);

should be

    $(document).on('page:change turbolinks:load', PayolaCheckout.initialize);

https://github.com/payolapayments/payola/blob/master/app/assets/javascripts/payola/checkout_button.js#L98

**Comment by eliotsykes** [comment]
Thanks for reporting @dakotalightning. PR #254 should handle this once its merged.
