### ISSUE TITLE
Allow user to change his or her credit card number?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [payolapayments/payola#285]
Is there a way to allow users to update their info? Currently, I can only allow a user to change their plan.

<div class="subscription-form">
<h3>Subscription Plan</h3>
  <%= form_for(resource, :as => resource_name, :url => change_plan_path, :html => {:method => :put, :role => 'form'}) do |f| %>
  <div class="form-group">
    <%= f.label 'Subscription Plan' %>
    <%= f.collection_select(:plan_id, Plan.all, :id, :name) %>
  </div>
      <%= f.submit 'Change Plan', :class => 'btn btn-primary' %>
   <% end %>
</div>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>

**Comment by eliotsykes** [comment]
Hi @RailsCod3rFuture, Payola does provide some assistance with updating cards, see https://github.com/payolapayments/payola/issues/130#issuecomment-234217777 and the `update_card` route.
