### ISSUE TITLE
out-of-the-box fail - "Owner must exist, Coupon must exist, and Affiliate must exist"

### ISSUE THREAD

**Issue by stephenamsel** [payolapayments/payola#289]
While trying to fix an earlier problem (Issue [283](https://github.com/payolapayments/payola/issues/283)), I tried building a test-app, starting from scratch with a new test-app containing only Payola, Papertrail, and a scaffold for the sellable model.
The only configuration-changes I included were the addition of secret and publishable keys to the Payola initializer.
Here is the model: (This is taking time, so I decided I'm selling hours of work.)
`class Manhour < ApplicationRecord
  include Payola::Sellable
end`
Here is the non-commented part of the config-file
`Payola.configure do |config|
  config.secret_key = '[REDACTED]'
  config.publishable_key = '[REDACTED]'
  
  config.subscribe 'charge.refunded' do |event|
    sale = Payola::Sale.find_by(stripe_id: event.data.object.id)
    sale.refund! unless sale.refunded?
  end
end`
and here is the show-page
`<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @manhour.price %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @manhour.permalink %>
</p>

<p>
  <strong>Name:</strong>
  <%= @manhour.name %>
</p>

<%= render 'payola/transactions/checkout', sellable: @manhour %>

<%= link_to 'Edit', edit_manhour_path(@manhour) %> |
<%= link_to 'Back', manhours_path %>`

When attempting to make a payment, here is the in-browser error-message:
Owner must exist, Coupon must exist, and Affiliate must exist

`Started POST "/payola/buy/manhour/test-2" for 127.0.0.1 at 2017-03-26 23:41:52 -0400
Processing by Payola::TransactionsController#create as */*
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"tqay8YNBSKvpRduFI9DeoQuQS3nZ4fA7rHrSdNZ+IsILywhJ9kO4NRt7/Mzy1IUWhisqvWHtJWBPpoIVHkVPaQ==", "stripeToken"=>"[redacted]", "stripeEmail"=>"test-2@example.com", "product_class"=>"manhour", "permalink"=>"test-2"}
  Payola::Affiliate Load (0.1ms)  SELECT  "payola_affiliates".* FROM "payola_affiliates" WHERE (lower(code) = lower(NULL)) ORDER BY "payola_affiliates"."id" ASC LIMIT ?  [["LIMIT", 1]]
  Manhour Load (0.1ms)  SELECT  "manhours".* FROM "manhours" WHERE "manhours"."permalink" = ? LIMIT ?  [["permalink", "test-2"], ["LIMIT", 1]]
  Payola::Coupon Load (0.1ms)  SELECT  "payola_coupons".* FROM "payola_coupons" WHERE (lower(code) = lower(NULL)) ORDER BY "payola_coupons"."id" ASC LIMIT ?  [["LIMIT", 1]]
   (0.1ms)  begin transaction
  Payola::Sale Exists (0.1ms)  SELECT  1 AS one FROM "payola_sales" WHERE "payola_sales"."guid" IS NULL LIMIT ?  [["LIMIT", 1]]
   (0.1ms)  rollback transaction
Completed 400 Bad Request in 29ms (Views: 0.2ms | ActiveRecord: 1.9ms)
`
This is a for a new object, created only for this single test, and a new email address.
The card-number was the Stripe Visa test-card, 4242424242424242 .
Any ideas what I am missing in my test-app?

I have redacted the stripe-token and both API keys here.

**Comment by stephenamsel** [comment]
I tried adding
`Rails.application.config.active_record.belongs_to_required_by_default = false`
to application.rb. It didn't help.

**Comment by eliotsykes** [comment]
Not sure this is it but might be worth a try. Is there a `new_framework_defaults.rb` initializer? If yes, try setting it there instead of `application.rb`. More details here: https://github.com/payolapayments/payola/issues/259#issuecomment-246621205

**Comment by Superpencil** [comment]
I can confirm there is an issue, I did not have the `new_framework_defaults.rb` file since I had upgraded to Rails 5 during the beta.

Adding this file as-is from a new Rails 5 app made my error worse:
`{"guid":null,"status":"pending","error":"Email can't be blank, Stripe token can't be blank, Owner must exist, Coupon must exist, and Affiliate must exist"}`
As before, when it is set to false without this file, my error was:
`{"guid":null,"status":"pending","error":"Email can't be blank and Stripe token can't be blank"}`

This is also an out-of-the-box new Payola install on a simple app following Payola's installation instructions...
