### ISSUE TITLE
Example of Async form to update credit card

### ISSUE THREAD

**Issue by adambedford** [payolapayments/payola#290]
Is there a good example of a form to asynchronously update the customer's credit card? i.e. fetch the token from stripe and POST to `subscriptions#update_card`.

I'm familiar with the existence of the `update_card` route and controller action, but unsure what the form should look like to fetch the token from Stripe.

Any help greatly appreciated! Thanks!

**Comment by adambedford** [comment]
Turns out this was straightforward and only requires `POST`ing to `payola.update_card_path(@subscription)`.

Here's an example of the form I'm using in HAML:

```ruby
= form_tag payola.update_card_path(@subscription), class: 'payola-onestep-subscription-form',
                             'data-payola-base-path' => '/payola',
                             'data-payola-plan-type' => @subscription.plan.plan_class,
                             'data-payola-plan-id' => @subscription.plan.id do

  %span.payola-payment-error

  .form-group
    = hidden_field_tag "stripeEmail", "owner@account11.com", data: { payola: "email" }

  .form-group
    = label_tag "number", "Card Number", class: "control-label"
    = text_field_tag "number", nil, type: "tel", data: { stripe: "number" }, class: "form-control"

  .row
    .col-md-6
      .form-group
        = label_tag "month", "Expiry Month", class: "control-label select"
        = select_month(Date.today, { add_month_numbers: true, prefix: "expiry" }, { class: "form-control select", data: { stripe: "exp_month" } })

    .col-md-6
      .form-group
        = label_tag "year", "Expiry Year", class: "control-label select"
        = select_year(Date.today, { start_year: Date.today.year, use_two_digit_numbers: true, prefix: "expiry" }, { class: "form-control select", data: { stripe: "exp_year" } })

  .row
    .col-md-6
      .form-group
        = label_tag "cvc", "CVC", class: "control-label"
        = text_field_tag "cvc", nil, type: "tel", data: { stripe: "cvc" }, class: "form-control"

  .text-right
    .form-group
      = link_to "Cancel", account_subscriptions_path, class: "btn btn-default"
      = button_tag "Update Card", class: "btn btn-primary"
```

**Comment by eliotsykes** [comment]
Thanks for sharing @adambedford 👍 , I expect this will useful documentation for others!

**Comment by NorCalDavid** [comment]
Thanks @adambedford , This has definitely helped but I am wondering if you could show me what your controller for this looks like.  I am getting an error and the redirect after updating the card number is failing.  The card number is getting changed but it is throwing the below error.

![screen shot 2017-07-20 at 3 33 37 pm](https://user-images.githubusercontent.com/5322371/28441880-01da3aea-6d62-11e7-898c-d101653ad87c.png)
