### ISSUE TITLE
Payola::CreateSubscription fails when :stripe_customer_id is provided

### ISSUE THREAD

**Issue by sayhiben** [payolapayments/payola#291]
While implementing Payola, I noticed that canceling a subscription and then resubscribing would create a new customer inside Stripe. After reading the source, it appeared that I should pass a `:stripe_customer_id` parameter to the checkout helper like so:

```ruby
  def subscribe_button(plan)
    options = {
      plan:         plan,
      button_class: 'btn btn-lg btn-block',
      button_text:  'Choose Plan',
      email:        current_user.email
    }
    if current_user.subscriptions.count > 0
      options.merge!(stripe_customer_id: current_user.subscriptions.last.stripe_customer_id)
    end

    render('payola/subscriptions/checkout', options)
  end
```

So far so good; the checkout button receives a `data-stripe_customer_id` attribute. However, when the button is clicked, it results in the following 500 error:

```
TypeError (normalize_opts expects a string or a hash):
  
stripe (2.0.1) lib/stripe/util.rb:203:in `normalize_opts'
stripe (2.0.1) lib/stripe/api_resource.rb:62:in `retrieve'
payola-payments (1.5.0) app/services/payola/create_subscription.rb:8:in `call'
payola-payments (1.5.0) app/controllers/concerns/payola/async_behavior.rb:34:in `create_object'
payola-payments (1.5.0) app/controllers/payola/subscriptions_controller.rb:19:in `create'
```

This is due to `Stripe::Util::normalize_opts` doing type checking to ensure the passed option is a String or Hash (as the error message says), when the passed object is a `Payola::EnvWrapper`.

One solution would be to pass `Payola.secret_key.to_s` to `Stripe::Customer#retrieve` in `Payola::CreateSubscription::call` rather than just `Payola.secret_key`, however I suspect there's potential to do something more along the lines of what's going on in #256.

**Comment by eliotsykes** [comment]
Thanks @sayhiben for digging into this and reporting.

Here's where the type checking is done: https://github.com/stripe/stripe-ruby/blob/d2cada1c1c8a3a3f25769a3622a02537c738af26/lib/stripe/util.rb#L198-L208

As @sayhiben pointed at, this is essentially what's returning false in the `when String` line (line 200):

```rb
String === EnvWrapper
```

One way to make the above expression return true is for `EnvWrapper` to be a subclass of `String`. Thoughts? Alternatives?

**Comment by SirRawlins** [comment]
Any more progress or thoughts on this folks? I'm running into the same issue trying to create a new subscription for a previous customer who's existing subscription has been cancelled, due to non-payment.

**Comment by kartikluke** [comment]
@eliotsykes Is there anyway to fix this?

**Comment by sayhiben** [comment]
@kartikluke I monkey patched by putting this at the top of `config/initializers/payola.rb`:

```
# Monkey patch Payola.secret_key; there are issues with EnvWrapper and the Stripe gem
unless Gem.loaded_specs['payola-payments'].version == Gem::Version.create('1.5.0')
  raise 'Payola gem version changed. Can Payola monkey patches be removed?'
end
module Payola
  class << self
    def secret_key
      @secret_key.to_s
    end
  end
end
```

**Comment by sayhiben** [comment]
@kartikluke Your PR looks like it should work just fine, and is narrower in scope. I'd like to see that get merged.

**Comment by kartikluke** [comment]
@sayhiben The reason for the narrower scope is because Stripe seems to be the only part that is throwing an error for now and this way EnvWrapper can continue to do what it's supposed to.

Maybe @eliotsykes can help get it merged. This is a pretty important part of the flow which isn't documented that much either. Passing the customer_id to start a new subscription allows you to have better tracking and customer doesn't have to fill details anymore.
