### ISSUE TITLE
How to know when subscription active / canceled / canceling?

### ISSUE THREAD

**Issue by meesterdude** [payolapayments/payola#295]
Hello,

I am trying to identify how to know when a subscription is active, canceled or being canceled. 

when i cancel via the view button and set it to be end of the term, the option `cancel_at_period_end` becomes true. But I see `canceled_at` and `ended_at`, and of course `trial_end` and `current_period_end` options as well, the first two are `nil` while the latter two are the same `DateTime` in the future (in my testing of course)

So, whats authoratative? is it the state machine? or some combination of those attributes? 

Specifically, i want to resolve:

* deny accounts access with ended or canceled subscriptions
* display message for accounts due to be canceled

I've scoured the source code, but still can't figure it out. Appreciate any insight!

**Comment by naterexw** [comment]
```subscription.state```

See [Stripe subscription states](https://stripe.com/docs/subscriptions/lifecycle#states)
