### ISSUE TITLE
error when doing a migration in rails 5.1.0

### ISSUE THREAD

**Issue by muriithiKabogo** [payolapayments/payola#300]
Cant do migrations
ERROR MESSAGE

rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreatePayolaSales < ActiveRecord::Migration[4.2]

StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreatePayolaSales < ActiveRecord::Migration[4.2]

Tasks: TOP => db:migrate
(See full trace by running task with --trace)

Help me fix

**Comment by alekseenko** [comment]
@muriithiKabogo I've created [pull request](https://github.com/payolapayments/payola/pull/302) that should resolve this issue. Meanwhile you can use [this fork](https://github.com/alekseenko/payola) in order to migrate properly. Just change
```
gem 'payola-payments'
```
to:
```
gem 'payola-payments', git: 'https://github.com/alekseenko/payola'
```
And then run `bundle install` again

**Comment by naterexw** [comment]
+1
