### ISSUE TITLE
Multiple plans per Subscription

### ISSUE THREAD

**Issue by alfredoreduarte** [payolapayments/payola#301]
I couldn't find an explanation or an older issue for this.

Is it possible to subscribe a customer to multiple plans in a single subscription? Like when you're charging for different features of an app on a single monthly subscription.

Right now if I want to subscribe to a plan, I make a POST request to `/subscribe/:plan_class/:plan_id.json`. That URL doesn't seem to indicate there's a way to pass an array of plans, like described here in Stripe's docs: https://stripe.com/docs/subscriptions/multiplan

```
Stripe::Subscription.create(
  customer: "cus_91elFtZU3tt11g",
  items: [
    {
      plan: "basic-monthly",
    },
    {
      plan: "additional-license",
      quantity: 2,
    },
  ]
)
```
Is this in the pipeline? Has anyone got something like this working?

**Comment by ameft** [comment]
I'm also interested in this feature that currently Payola doesn't support.
