### ISSUE TITLE
Cannot get emails to work.

### ISSUE THREAD

**Issue by jackdweber** [payolapayments/payola#303]
I have tried many things in the payola.rb file under the initializers.
Here are some examples I've tried
config.send_email_for :receipt

  config.subscribe 'payola.subscription.finished' do |sale|
    WeeklyMailer.weeklyEmail(current_user).deliver_now
  end

  config.subscribe 'payola.basic.sale.finished' do |sale|
    WeeklyMailer.weeklyEmail(current_user).deliver_now
  end

Within my configuration block. The mailer is one I know works. Im not sure if there is a setting somewhere I need to change. Thanks.

**Comment by jackdweber** [comment]
I have figured out I need something like this
    config.subscribe 'payola.subscription.activated'
to send an email after a user signs update for a subscription.
    config.subscribe 'payola.subscription.active'
loops the program and
    config.subscribe 'payola.subscription.activate'
    config.subscribe 'payola.subscription.activated'
do not work

**Comment by jackdweber** [comment]
config.subscribe 'payola.subscription.active'
was the correct one, just couldn't use devise during it.

**Comment by cs0511** [comment]
hi @jackdweber 

I just encountered same issue. Followed the doc [here](https://github.com/payolapayments/payola/wiki/Configuration-options), but no success. 

Could you give some sample code how you solve it?

**Comment by cs0511** [comment]
For anyone who has same issue,
the doc seems too old, events supported are 
  # state :pending
  # state :processing
  # state :active
  # state :canceled
  # state :errored

For example

```
config.subscribe 'payola.subscription.active' do |subscription|
    SuckerPunch.logger.info('payola.subscription.active')
    AdminMailer.sale_finished().deliver_now
end
```

It should monitor the `payola_subscriptions` table's `state` column, and these five events are the legal value for this column.

**Comment by jackdweber** [comment]
Yep did the same thing! Sorry I didn't reply sooner.
