### ISSUE TITLE
Update Card on Subscription is just creating a new subscription.  Is there a sample form for Updating a card #

### ISSUE THREAD

**Issue by NorCalDavid** [payolapayments/payola#317]

**Comment by NorCalDavid** [comment]
I actually made some changes based on another issue ticket I found and it is updating the CC number on stripe but I am getting the attached error and the form is not redirecting.  Can you provide any insight?
![screen shot 2017-07-20 at 3 33 37 pm](https://user-images.githubusercontent.com/5322371/28441735-1d40a054-6d61-11e7-99f3-3f30071a00e2.png)

**Comment by naterexw** [comment]
[Try looking at this](https://groups.google.com/forum/#!topic/payola-payments/PYElgdxr5qE)
