### ISSUE TITLE
404 Error on /payola/events

### ISSUE THREAD

**Issue by chrismahon** [payolapayments/payola#319]
Hi,

I'm getting a 404 error on the follow URL when creating a new subscription:

http://localhost:3000/payola/events?action=billing&controller=plans

This only appears to happen when I have my User model setup like this:

`has_one :subscription, ->(sub) { where.not(stripe_id: nil) }, class_name: Payola::Subscription, foreign_key: :owner_id`

If I change this to the following, I don't get the 404 error:

`has_one :subscription, foreign_key: :owner_id, class_name: "Payola::Subscription"`

In both scenarios the subscription is setup properly but only the second scenario actually redirects the user properly once the subscription has been setup.

Payola is mounted in Routes.rb like this:

`mount Payola::Engine => '/payola', as: :payola`

Any idea what is the causing this? The reason I went with the first has_one method was that if a customer entered a card that was declined, I would end up getting duplicate entries in the payola_subscriptions table which meant that something like the following would throw an error if the user had two subscriptions:

`<%= current_user.subscription.current_period_end.strftime('%d %B, %Y') %>`

Any idea what is causing this 404 and how to resolve it?

Thanks,
Chris

**Comment by Alagaesia93** [comment]
I have the same error. Is there any update?
