### ISSUE TITLE
Any plans to cut a new tag?

### ISSUE THREAD

**Issue by MSeneadza** [payolapayments/payola#332]
Hi,

I was just wondering if there are any plans to release a new version.  I just ran into a problem that was fixed in master back in July.  I've updated my Gemfile to point at master's latest commit but I'm just curious since it's been over a year since the 1.5.0 tag was cut.

**Comment by peterkeen** [comment]
Done.

**Comment by MSeneadza** [comment]
Thanks.  You're a gentleman and a scholar!
