### ISSUE TITLE
undefined method `event_retriever=' for StripeEvent:Module

### ISSUE THREAD

**Issue by nerboda** [payolapayments/payola#335]
The error is thrown when I run `rails g payola:install` and is caused by an update to the `stripe_event` gem where `StripeEvent.event_retriever` was changed to `event_filter`. See the commit [here](https://github.com/integrallis/stripe_event/commit/2c930df4bb694c01cb3dfe733ba90c8dbda0d38e#diff-6ef0c2bf3583d5f1bdf5936fe318fc3d)

Should be a simple fix, working on that now.

**Comment by NemyaNation** [comment]
I'm still getting this error when using the Rails Composer gem!

Please see -> https://github.com/RailsApps/rails-composer/issues/276
for the details. I've been struggling with this for an enitre day and I'm tired.

**Comment by NemyaNation** [comment]
"Bundler::GemRequireError: There was an error while trying to load the gem 'payol
a-payments'.
Gem Load Error is: undefined method `event_retriever=' for StripeEvent:Module
Did you mean?  event_filter="

**Comment by NemyaNation** [comment]
Tried using old version of payola-payment but error is still present!

Please help me finally fix this!

**Comment by nerboda** [comment]
@peterkeen any plans to release a new version with this fix?

**Comment by scervera** [comment]
I'm running into this issue. I'm new to using the payola-payments gem. I don't see a resolution in this issue thread. Is a fix coming? Thanks for your work on this.

**Comment by nerboda** [comment]
@NemyaNation what version? And what version of the `stripe_event` gem do you have?

In order for bundler install the version with this fix, you'll need to use `gem 'payola-payments', :git => 'git@github.com:payolapayments/payola.git'` in your gemfile because a new version hasn't been added to rubygems.org yet.

**Comment by shantilal-narola** [comment]
Hello I have tried to  replace gem 'payola-payments with gem 'payola-payments', :git => 'git@github.com:payolapayments/payola.git' in your Gemfile.
after that i am facing the issue like:

-- [](4.2)
-- [](4.2)
rake aborted!
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x007fae9c6fc550>

**Comment by scervera** [comment]
Thank you, @nerboda. Making the change in my Gemfile did the trick. Problem resolved.

**Comment by ianwalter** [comment]
@nerboda Why did you close the issue if the fix hasn't been released?

**Comment by jennykortina** [comment]
Is this issue going to be patched on master?

**Comment by richardonrails** [comment]
Can a new release please be made so that we can run from a released version instead of from master?

Right now having to do `gem 'payola-payments', github: 'payolapayments/payola', ref: 'a1dd9ff5753e649a733ba41f711dbb6f7833b009'` which is not ideal.

**Comment by asecondwill** [comment]
@peterkeen 
Feels wrong that this is closed.  Everybody installing the gem for the first time will have this error?

**Comment by nerboda** [comment]
@asecondwill just opened a pull request changing the install instructions.
