### ISSUE TITLE
Migrations broken for Rails 4.2

### ISSUE THREAD

**Issue by mrideout** [payolapayments/payola#345]
af67b1a4601932f23d0533327557280bc5f5c756 broke migrations in for Rail 4.2.

```
$ bundle exec rake db:migrate
Expected string default value for '--jbuilder'; got true (boolean)
Expected string default value for '--serializer'; got true (boolean)
-- [](4.2)
-- [](4.2)
rake aborted!
```

I worked around the issue by reversing the commit (`git revert af67b1a4601932f23d0533327557280bc5f5c756`).

I haven't worked with Rails 5.1 yet, so there may be a more elegant solution, but it looks like [something like this](https://github.com/thoughtbot/clearance/commit/b0ce189c69d52155660232604cc30d729d6b4221) would allow for compatibility with both Rails versions. 

If anyone else runs into this issue and wants to use my workaround, then feel free to do so by adding the following to your Gemfile:

> gem 'payola-payments', :git => 'https://github.com/mrideout/payola'

Thanks,

Matt

**Comment by eliotsykes** [comment]
For anyone wanting to avoid forking, an alternative fix is possible with this initializer:

https://gist.github.com/eliotsykes/6878a877ec1efd2f36004dd098896623
