### ISSUE TITLE
Send Custom Metadata to Stripe

### ISSUE THREAD

**Issue by boethius** [payolapayments/payola#346]
Hi, we are implementing an affiliate system and it requires some data to be sent along with the payments. 

The affiliate system requires a hidden field to be included in the form and a javascript that loads some tracking data into that field to be passed along to stripe, where a webhook awaits to validate it.

It gives the following PHP example to be passed along with the amount, currency etc.:

```
'metadata' => $_POST['idev_custom']
```

I've tried the following approaches without success:

1. Override the `StartSubscription` and pass along the as one of the params. This works, but I get a `404`.
2. Then I realized the view that is sending the variables to stripe needs to change as well, so I tried adding it there and I get an invalid hash.
3. I then tried to added it to the signed custom fields, but I'm not sure that is what it is for and the documentation for it is confusing me on how to actually do it.

Any input would greatly be appreciated.

Thanks!

**Comment by Rhoxio** [comment]
Without monkey-patching your way into one of the outbound calls to Stripe within the Payola lib, this does not appear to be explicitly possible in the same flow as the payments. 

I had a similar issue and sent the metadata needed along in a separate API call to Stripe after the webhook response for whatever action (Subscription creation in my case) you are taking resolves. Save the metadata to be POSTed somewhere (Redis?) and push it in when your webhook resolves. You should have the data you need at that point to simply use the Stripe lib to make the call and set the metadata for whatever object you are attempting to give metadata to.
