### ISSUE TITLE
stripeToken required for new customer with paid subscription

### ISSUE THREAD

**Issue by cammand** [payolapayments/payola#347]
Also the stripe logs do not show any of the requests.

My controller:

class SubscriptionsController < ApplicationController
  # bring in the `render_payola_status` helper.
include Payola::StatusBehavior

def new

    @plan = SubscriptionPlan.first
  end

  def create
    # do any required setup here, including finding or creating the owner object
    owner = current_user # this is just an example for Devise

    # set your plan in the params hash
    params[:plan] = SubscriptionPlan.find_by(id: params[:plan_id])
    p params[:plan]

    # call Payola::CreateSubscription
    subscription = Payola::CreateSubscription.call(params, owner)
    p subscription

    # Render the status json that Payola's javascript expects
    render_payola_status(subscription)

 end

end
How exactly does it work? Does payola take the form params and pass it to Stripe? In this case, it looks like nothing is being passed to stripe? Plus I am not getting very much logs from the payola so it is difficult for me to decipher the cause of my error.

Active jobs is being run properly. And the error shows up after active jobs have been run successfully, until then the database states pending.

**Comment by Rhoxio** [comment]
A few things:

Do you have the appropriate Stripe credentials set in your env? 

It will poll a set number of times (50?) if you aren't receiving Webhook responses that amend the database appropriately. Ensure that you have webhooks configured correctly. If you are testing on a local machine, you will need to set up ngrok or something.

Stripe itself must make a specific request to their servers and retrieve a token before any transactions can happen in your app. That's what the stripeToken you are missing is.
