### ISSUE TITLE
Handle invalid cards when creating new subscriptions

### ISSUE THREAD

**Issue by peterkeen** [payolapayments/payola#58]
Now that a subscription inherits the customer from previous subscriptions (see #57) there exists the possibility that creating a subscription will result in a `Stripe::InvalidRequestError` because their card is no longer valid, or was deleted or something.

Gracefully handle this by propagating the error up to the JS and throwing some sort of event that the application can catch to redirect to a page with a payment form.

Also `Payola::CreateSubscription` needs to do the right thing if it's given a token for a customer with an existing subscription. Namely, assign the card to the existing customer.

**Comment by jagthedrummer** [comment]
How would I go about getting a subscription to inherit the customer from a previous subscription? Does this come into play if someone has canceled their subscription and then want to start a new one?

**Comment by peterkeen** [comment]
@jagthedrummer it should happen automatically. See [Payola::StartSubscription][1] for how it works.

[1]: https://github.com/peterkeen/payola/blob/master/app/services/payola/start_subscription.rb#L58-L62
