### ISSUE TITLE
Clarify docs for one time payments

### ISSUE THREAD

**Issue by DanielKehoe** [payolapayments/payola#89]
The wiki page for one time payments shows:

```
<%= form_for @whatever,
    html: {
      class: 'payola-payment-form',
      'data-payola-base-path' => main_app.payola_path,
      'data-payola-product' => @product.product_class,
      'data-payola-permalink' => @product.permalink
    } do |f| %>
```

Could you please offer an example for the values `main_app.payola_path`, `@product.product_class`, and `@product.permalink`.

If my application is named `RailsStripe` should I have:
`'data-payola-base-path' => RailsStripe.payola_path`?

If I have a class named `Product` for my product, and my controller `new` action includes `@product = Product.first` and it has attributes `name` and `permalink` do I use:
`'data-payola-product' => @product.class`?

**Comment by peterkeen** [comment]
Permalink is a required attribute for sellables. `product_class` gets mixed into your product when you `include Payola::Sellable` so you should be able to just say `@product.product_class`. The base path should be set to `payola_path`, assuming you have `as: :payola` in the mount in `config/routes.rb`.

**Comment by thehalvo** [comment]
Yeah I was confused by this as well :)

**Comment by peterkeen** [comment]
All three are defined for you so you can use that example
verbatim. Permalink is a required attribute for a Payola::Sellable,
product_class is internally defined by Payola::Sellable, and payola_path is
generated automatically when you mount Payola::Engine in your routes file.

**Comment by lukelove** [comment]
Add this to the routes file `mount Payola::Engine => '/payola'`
